# Generated by Django 5.1.7 on 2025-04-03 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spinapp', '0003_uploadedcsv'),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_number', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='UploadedCSV',
        ),
    ]
