# Generated by Django 5.1.7 on 2025-04-04 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spinapp', '0006_remove_user_email_user_territory_alter_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
    ]
